name: Inspect PR
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [ opened, reopened ]
  paths:
    - 'backend/**'

jobs:
  first_job:
    name: My first job
  second_job:
    name: My second job
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
        output1: ${{ steps.step1.outputs.test }}
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
        output2: ${{ steps.step2.outputs.test }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.second_job.outputs.output1}} ${{needs.second_job.outputs.output2}}